# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('account_street', models.CharField(max_length=50)),
                ('account_state', models.CharField(max_length=50)),
                ('account_city', models.CharField(max_length=50)),
                ('account_zip', models.CharField(max_length=50)),
                ('checks_bounced', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_amount', models.CharField(max_length=50)),
                ('check_number', models.CharField(max_length=50)),
                ('cashier_name', models.CharField(max_length=50)),
                ('check_status', models.CharField(max_length=50)),
                ('letter_date1', models.CharField(max_length=50)),
                ('letter_date2', models.CharField(max_length=50)),
                ('letter_date3', models.CharField(max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Client')),
                ('store_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Account')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_position', models.CharField(max_length=50)),
                ('user_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='store_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.User'),
        ),
        migrations.AddField(
            model_name='check',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.User'),
        ),
        migrations.AddField(
            model_name='account',
            name='acount_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Store'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Bank'),
        ),
    ]
