# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_account',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_user',
        ),
    ]
