# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20171024_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_status',
            field=models.BooleanField(default=False),
        ),
    ]
