# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_check_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_street',
            field=models.CharField(max_length=50),
        ),
    ]
