# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_auto_20171204_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='letter_date1',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
