# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_auto_20171204_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='letter_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='letter_date3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
