# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0008_auto_20171204_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='letter_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='letter_date2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
