# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_auto_20171204_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='letter_date1',
            new_name='letter_date_1',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='letter_date2',
            new_name='letter_date_2',
        ),
        migrations.RenameField(
            model_name='check',
            old_name='letter_date3',
            new_name='letter_date_3',
        ),
    ]
