# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0011_auto_20171204_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='routing_number',
        ),
        migrations.AddField(
            model_name='bank',
            name='routing_number',
            field=models.IntegerField(default=1, max_length=9),
        ),
    ]
